name: add pics to issue from title

on: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      issueNumber:
        description: 'Issue number to update'
        required: true
        type: number
        
  # This workflow is also triggered on issue creation.
  issues:
    types: [opened, edited]

jobs:
  update-issue-description:
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Detect title changes
      if: ${{ github.event.changes.title }} == ''
      run: exit 0

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get issue number
      id: get-issue-number
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "This workflow was manually triggered with issue number ${{ github.event.inputs.issueNumber }}"
          echo "issueNumber=${{ github.event.inputs.issueNumber }}" >> $GITHUB_OUTPUT
        else
          echo "This workflow was triggered by issue ${{ github.event.issue.number }}"
          echo "issueNumber=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
        fi
      
    - name: Get issue title
      id: get-issue-title
      run: |
        echo "issueTitle=$(gh issue view --json title -t '{{.title}}' ${{ steps.get-issue-number.outputs.issueNumber }} )" >> $GITHUB_OUTPUT

    - name: Get issue picture
      id: get-issue-title-picture
      run: |
        curl -H "Authorization: ${{ secrets.PEXELS_KEY }}" \
          --data-urlencode "query=${{ steps.get-issue-title.outputs.issueTitle }}"
          "https://api.pexels.com/v1/search?per_page=1" | jq -r '.photos[0].src.original' > url
        cat url
        
        echo -n "issueTitlePicture=" >> $GITHUB_OUTPUT
        cat url >> $GITHUB_OUTPUT

    - name: Update issue picture in body
      run: |
        echo "![${{ steps.get-issue-title.outputs.issueTitle }}](${{ steps.get-issue-title-picture.outputs.issueTitlePicture }})" | \
        gh issue edit "${{ steps.get-issue-number.outputs.issueNumber }}" --body-file -
