name: add pics to issue from title

on: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      issueNumber:
        description: 'Issue number to update'
        required: true
        type: number
        
  # This workflow is also triggered on issue creation.
  issues:
    types: [opened]

jobs:
  update-issue-description:
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get issue number
      id: get-issue-number
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "This workflow was manually triggered with issue number ${{ github.event.inputs.issueNumber }}"
          echo "issueNumber=${{ github.event.inputs.issueNumber }}" >> $GITHUB_OUTPUT
        else
          echo "This workflow was triggered by issue ${{ github.event.issue.number }}"
          echo "issueNumber=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
        fi
      
    - name: Get issue title
      id: get-issue-title
      run: |
        echo "issueTitle=$(gh issue view --json title -t '{{.title}}' ${{ steps.get-issue-number.outputs.issueNumber }})" >> $GITHUB_OUTPUT

    - name: Update issue picture in body
      run: |
        echo "![${{ steps.get-issue-title.outputs.issueTitle }}](https://images.pexels.com/photos/5194490/pexels-photo-5194490.jpeg)" | \
        gh issue edit "${{ steps.get-issue-number.outputs.issueNumber }}" --body-file -
