name: add pics to issue from title

on: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      issueNumber:
        description: 'Issue number to update'
        required: true
        type: number
        
  # This workflow is also triggered on issue creation.
  issues:
    types: [opened, edited]

jobs:
  update-issue-description:
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Detect title changes
      if: ${{ github.event.changes.title }} == ''
      run: exit 0

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get issue number
      id: get-issue-number
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "This workflow was manually triggered with issue number ${{ github.event.inputs.issueNumber }}"
          echo "issueNumber=${{ github.event.inputs.issueNumber }}" >> $GITHUB_OUTPUT
        else
          echo "This workflow was triggered by issue ${{ github.event.issue.number }}"
          echo "issueNumber=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
        fi
      
    - name: Get issue title
      id: get-issue-title
      run: |
        echo "issueTitle=$(gh issue view --json title -t '{{.title}}' ${{ steps.get-issue-number.outputs.issueNumber }} )" >> $GITHUB_OUTPUT

    - name: Get issue picture
      id: get-issue-recipe
      run: |
        curl -v --header "X-RapidAPI-Host: food-recipes-with-images.p.rapidapi.com" \
          --header "X-RapidAPI-Key: ${{ secrets.FOOD_RECIPES_KEY }}" \
          --get \
          --data-urlencode "q=${{ steps.get-issue-title.outputs.issueTitle }}" \
          --url "https://food-recipes-with-images.p.rapidapi.com/" | jq -r '.' > recipe

        cat recipe
        echo -n "issueTitlePicture=https:" >> $GITHUB_OUTPUT
        jq -r '.d[0].Image' recipe >> $GITHUB_OUTPUT

    - name: Update issue picture in body
      run: |
        cat << EOF > issue-body.md
          ![${{ steps.get-issue-title.outputs.issueTitle }}](${{ steps.get-issue-recipe.outputs.issueTitlePicture }})"
          
          # ${{ steps.get-issue-title.outputs.issueTitle }}
          
          ```[tasklist]
          ### Ingredients
          $(jq -r '.d[0].Ingredients | values[] |= "- [ ] " + . | values[]' recipe)
          ```
          ### Instructions
          
          $(jq -r '.d[0].Instructions' recipe)
        EOF

        cat issue-body.md
        
        gh issue edit "${{ steps.get-issue-number.outputs.issueNumber }}" --body-file issue-body.md
